# Generated by Django 4.2.30 on 2026-08-27 06:49

import courrier.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('SECRETARIAT_CENTRAL', 'Secrétariat Central'), ('SECRETAIRE_DC', 'Secrétaire du Directeur de Cabinet (DC)'), ('DC', 'Directeur de Cabinet (DC)'), ('SECRETAIRE_MINISTRE', 'Secrétaire Particulier du Ministre'), ('MINISTRE', 'Ministre'), ('DIRECTEUR', 'Directeur de Département'), ('AGENT', 'Agent')], default='AGENT', max_length=50, verbose_name='Rôle au sein du Ministère')),
                ('service_direction', models.CharField(blank=True, help_text='Pour les directeurs et agents, indique la direction (ex: DAF, DEC, etc.)', max_length=150, null=True, verbose_name="Service / Direction d'appartenance")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Généré automatiquement ou saisi manuellement', max_length=100, unique=True, verbose_name="Référence / Numéro d'enregistrement")),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation / Objet du courrier')),
                ('resume', models.TextField(blank=True, verbose_name='Résumé analytique')),
                ('expediteur', models.CharField(max_length=200, verbose_name='Expéditeur (Institution ou Nom)')),
                ('destinataire_initial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destinataire ou Orientation Initiale')),
                ('confidentialite', models.CharField(choices=[('NORMAL', 'Normal'), ('CONFIDENTIEL', 'Confidentiel'), ('TRES_CONFIDENTIEL', 'Très Confidentiel')], default='NORMAL', max_length=50, verbose_name='Niveau de Confidentialité')),
                ('statut', models.CharField(choices=[('ARRIVE', 'Enregistré (Secrétariat Central)'), ('EN_COURS_DC', "En cours d'analyse (DC)"), ('ANALYSE_VALIDE', 'Analyse validée (En attente décision)'), ('DECIDE', "Décidé (En attente d'affectation)"), ('AFFECTE', 'Affecté aux services'), ('TERMINE', 'Traité')], default='ARRIVE', max_length=50, verbose_name='Statut du traitement')),
                ('date_arrivee', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure de réception physique')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement dans le système")),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courriers_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Courrier',
                'verbose_name_plural': 'Courriers',
                'ordering': ['-date_arrivee'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Contenu de la notification')),
                ('lu', models.BooleanField(default=False, verbose_name='Marqué comme lu')),
                ('date_notification', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('courrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_associees', to='courrier.courrier', verbose_name='Courrier concerné')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_notification'],
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='ex: ENREGISTREMENT, VALIDATION_ANALYSE, DECISION, AFFECTATION', max_length=100, verbose_name='Action réalisée')),
                ('description', models.TextField(verbose_name="Description détaillée de l'action")),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date et heure de l'action")),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='courrier.courrier', verbose_name='Courrier concerné')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Auteur de l'action")),
            ],
            options={
                'verbose_name': "Historique d'audit",
                'verbose_name_plural': "Historiques d'audit",
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='FicheAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations_dc', models.TextField(blank=True, verbose_name='Observations du Directeur de Cabinet')),
                ('propositions_dc', models.TextField(blank=True, verbose_name="Propositions d'orientation du DC")),
                ('valide', models.BooleanField(default=False, verbose_name='Analyse validée par le DC')),
                ('date_analyse', models.DateTimeField(auto_now_add=True, verbose_name="Date de rédaction de l'analyse")),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name="Date de validation de l'analyse")),
                ('analyse_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analyses_redigees', to=settings.AUTH_USER_MODEL, verbose_name='Analysé par')),
                ('courrier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_analyse', to='courrier.courrier', verbose_name='Courrier')),
            ],
            options={
                'verbose_name': "Fiche d'analyse",
                'verbose_name_plural': "Fiches d'analyse",
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la pièce jointe')),
                ('fichier', models.FileField(upload_to=courrier.models.secure_file_upload_path, verbose_name='Fichier PDF numérisé')),
                ('taille_octets', models.PositiveIntegerField(default=0, verbose_name='Taille du fichier (en octets)')),
                ('date_televersement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='courrier.courrier', verbose_name='Courrier associé')),
            ],
            options={
                'verbose_name': 'Document joint',
                'verbose_name_plural': 'Documents joints',
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions_finales', models.TextField(verbose_name='Décisions et Instructions finales du Ministre')),
                ('date_decision', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de la décision')),
                ('courrier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='courrier.courrier', verbose_name='Courrier')),
                ('fiche_analyse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_associee', to='courrier.ficheanalyse', verbose_name="Fiche d'analyse d'appui")),
                ('signe_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions_prises', to=settings.AUTH_USER_MODEL, verbose_name='Signé / Décidé par')),
            ],
            options={
                'verbose_name': 'Décision finale',
                'verbose_name_plural': 'Décisions finales',
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_concerne', models.CharField(max_length=150, verbose_name='Direction / Service concerné (ex: DAF, DGM, etc.)')),
                ('statut_traitement', models.CharField(choices=[('RECU', 'Reçu par le service'), ('EN_COURS', 'En cours de traitement'), ('TRAITE', 'Traité / Classé')], default='RECU', max_length=50, verbose_name="Statut d'exécution")),
                ('date_affectation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'affectation")),
                ('date_reception', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture / Réception')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de finalisation')),
                ('note_traitement', models.TextField(blank=True, verbose_name="Commentaire d'exécution ou rapport de traitement")),
                ('affecte_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_ordonnees', to=settings.AUTH_USER_MODEL, verbose_name='Affecté par')),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='courrier.courrier', verbose_name='Courrier')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_generees', to='courrier.decision', verbose_name="Décision d'appui")),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_recues', to=settings.AUTH_USER_MODEL, verbose_name='Directeur / Service Destinataire')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
            },
        ),
    ]
