# Generated by Django 4.2.30 on 2026-08-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courrier',
            name='expediteur',
        ),
        migrations.AddField(
            model_name='courrier',
            name='expediteur_institution',
            field=models.CharField(blank=True, max_length=200, verbose_name="Institution de l'expéditeur"),
        ),
        migrations.AddField(
            model_name='courrier',
            name='expediteur_nom',
            field=models.CharField(default=1, max_length=200, verbose_name="Nom de l'expéditeur"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courrier',
            name='expediteur_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone de l'expéditeur"),
        ),
    ]
