# Generated by Django 4.2.30 on 2026-08-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0002_remove_courrier_expediteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='priorite',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('TRES_URGENT', 'Très Urgent')], default='NORMAL', max_length=50, verbose_name='Niveau de priorité'),
        ),
    ]
