# Generated by Django 4.2.30 on 2026-08-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0003_courrier_priorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courrier',
            name='confidentialite',
        ),
    ]
