# Generated by Django 4.2.30 on 2026-08-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0004_remove_courrier_confidentialite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courrier',
            name='destinataire_initial',
        ),
    ]
