# Generated by Django 4.2.30 on 2026-08-31 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0005_remove_courrier_destinataire_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='instruction_standard',
            field=models.CharField(choices=[('MEN_PARLER', "M'en parler avant traitement"), ('EN_INSTANCE', 'En instance'), ('POUR_ATTRIBUTION', 'Pour attribution / À traiter'), ('A_CLASSER', 'À classer'), ('AUTRE', 'Autre (voir instructions finales)')], default='POUR_ATTRIBUTION', max_length=50, verbose_name='Action rapide / Instruction standard'),
        ),
        migrations.AddField(
            model_name='ficheanalyse',
            name='direction_proposee',
            field=models.CharField(blank=True, choices=[('Cabinet du Ministre', 'Cabinet du Ministre'), ('Secrétariat Général', 'Secrétariat Général'), ('DAAF', 'DAAF'), ('DPDT', 'DPDT'), ('DPT', 'DPT'), ('DRICEHB', 'DRICEHB'), ('DLPL', 'DLPL'), ('DPAC', 'DPAC'), ('CNCIA', 'CNCIA'), ('DERPC', 'DERPC'), ('DPC', 'DPC'), ('CENALAC', 'CENALAC'), ('DRAC Grand-Lomé', 'DRAC Grand-Lomé'), ('DRAC Maritime', 'DRAC Maritime'), ('DRAC Plateaux', 'DRAC Plateaux'), ('DRAC Centrale', 'DRAC Centrale'), ('DRAC Kara', 'DRAC Kara'), ('DRAC Savanes', 'DRAC Savanes'), ('PRMP', 'PRMP'), ('CPMP', 'CPMP'), ('CCMP', 'CCMP'), ('Agent Comptable', 'Agent Comptable'), ('FPDT', 'FPDT'), ('FNPC', 'FNPC'), ('CNACET', 'CNACET'), ('IRES-RDEC', 'IRES-RDEC'), ('BUTODRA', 'BUTODRA'), ('CNPC', 'CNPC'), ('CRFTH', 'CRFTH'), ('CCT', 'CCT'), ('Autre', 'Autre (à préciser)')], max_length=150, null=True, verbose_name='Direction / Service proposé (Optionnel)'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_recues', to=settings.AUTH_USER_MODEL, verbose_name='Directeur / Service Destinataire'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='service_concerne',
            field=models.CharField(choices=[('Cabinet du Ministre', 'Cabinet du Ministre'), ('Secrétariat Général', 'Secrétariat Général'), ('DAAF', 'DAAF'), ('DPDT', 'DPDT'), ('DPT', 'DPT'), ('DRICEHB', 'DRICEHB'), ('DLPL', 'DLPL'), ('DPAC', 'DPAC'), ('CNCIA', 'CNCIA'), ('DERPC', 'DERPC'), ('DPC', 'DPC'), ('CENALAC', 'CENALAC'), ('DRAC Grand-Lomé', 'DRAC Grand-Lomé'), ('DRAC Maritime', 'DRAC Maritime'), ('DRAC Plateaux', 'DRAC Plateaux'), ('DRAC Centrale', 'DRAC Centrale'), ('DRAC Kara', 'DRAC Kara'), ('DRAC Savanes', 'DRAC Savanes'), ('PRMP', 'PRMP'), ('CPMP', 'CPMP'), ('CCMP', 'CCMP'), ('Agent Comptable', 'Agent Comptable'), ('FPDT', 'FPDT'), ('FNPC', 'FNPC'), ('CNACET', 'CNACET'), ('IRES-RDEC', 'IRES-RDEC'), ('BUTODRA', 'BUTODRA'), ('CNPC', 'CNPC'), ('CRFTH', 'CRFTH'), ('CCT', 'CCT'), ('Autre', 'Autre (à préciser)')], max_length=150, verbose_name='Direction / Service concerné'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='instructions_finales',
            field=models.TextField(blank=True, null=True, verbose_name='Décisions et Instructions finales (Commentaire libre)'),
        ),
        migrations.AlterField(
            model_name='ficheanalyse',
            name='propositions_dc',
            field=models.TextField(blank=True, verbose_name="Propositions d'orientation supplémentaires"),
        ),
    ]
