# Generated by Django 4.2.30 on 2026-08-31 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0006_decision_instruction_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_recues', to=settings.AUTH_USER_MODEL, verbose_name='Agent destinataire (Optionnel)'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='service_concerne',
            field=models.CharField(blank=True, choices=[('Cabinet du Ministre', 'Cabinet du Ministre'), ('Secrétariat Général', 'Secrétariat Général'), ('DAAF', 'DAAF'), ('DPDT', 'DPDT'), ('DPT', 'DPT'), ('DRICEHB', 'DRICEHB'), ('DLPL', 'DLPL'), ('DPAC', 'DPAC'), ('CNCIA', 'CNCIA'), ('DERPC', 'DERPC'), ('DPC', 'DPC'), ('CENALAC', 'CENALAC'), ('DRAC Grand-Lomé', 'DRAC Grand-Lomé'), ('DRAC Maritime', 'DRAC Maritime'), ('DRAC Plateaux', 'DRAC Plateaux'), ('DRAC Centrale', 'DRAC Centrale'), ('DRAC Kara', 'DRAC Kara'), ('DRAC Savanes', 'DRAC Savanes'), ('PRMP', 'PRMP'), ('CPMP', 'CPMP'), ('CCMP', 'CCMP'), ('Agent Comptable', 'Agent Comptable'), ('FPDT', 'FPDT'), ('FNPC', 'FNPC'), ('CNACET', 'CNACET'), ('IRES-RDEC', 'IRES-RDEC'), ('BUTODRA', 'BUTODRA'), ('CNPC', 'CNPC'), ('CRFTH', 'CRFTH'), ('CCT', 'CCT'), ('Autre', 'Autre (à préciser)')], max_length=150, null=True, verbose_name='Direction / Service concerné (Optionnel)'),
        ),
    ]
