# Generated by Django 6.0.1 on 2026-09-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0008_secure_document_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SECRETARIAT_CENTRAL', 'Secrétariat Central'), ('SECRETAIRE_DC', 'Secrétaire du Directeur de Cabinet (DC)'), ('DC', 'Directeur de Cabinet (DC)'), ('SECRETAIRE_SG', 'Secrétaire du Secrétaire Général (SG)'), ('SG', 'Secrétaire Général (SG)'), ('SECRETAIRE_MINISTRE', 'Secrétaire Particulier du Ministre'), ('MINISTRE', 'Ministre'), ('DIRECTEUR', 'Directeur de Département'), ('AGENT', 'Agent')], default='AGENT', max_length=50, verbose_name='Rôle au sein du Ministère'),
        ),
    ]
