# Generated by Django 4.2.30 on 2026-09-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='statut',
            field=models.CharField(choices=[('ARRIVE', 'Enregistré (Secrétariat Central)'), ('REJETE_SECRETAIRE', 'Rejeté par Secrétariat pour correction'), ('TRANSMIS_DC', 'Transmis au DC / SG'), ('EN_COURS_DC', "En cours d'analyse (DC/SG)"), ('ANALYSE_VALIDE', 'Analyse validée (DC/SG)'), ('TRANSMIS_MINISTRE', 'Transmis au Ministre'), ('DECIDE', "Décidé (En attente d'affectation)"), ('AFFECTE', 'Affecté aux services'), ('TERMINE', 'Traité')], default='ARRIVE', max_length=50, verbose_name='Statut du traitement'),
        ),
    ]
