# Generated by hand: add motif_rejet, comite fields and FicheAnalyseSG model
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0010_alter_courrier_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de rejet par le secrétariat'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='comite',
            field=models.TextField(blank=True, null=True, verbose_name='Compte-rendu / Comité'),
        ),
        migrations.CreateModel(
            name='FicheAnalyseSG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations_sg', models.TextField(blank=True, verbose_name='Observations du Secrétaire Général')),
                ('propositions_sg', models.TextField(blank=True, verbose_name='Propositions du Secrétaire Général')),
                ('direction_proposee', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direction / Service proposé (Optionnel)')),
                ('valide', models.BooleanField(default=False, verbose_name='Analyse validée par le SG')),
                ('date_analyse', models.DateTimeField(auto_now_add=True, verbose_name='Date de rédaction de l\'analyse')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation de l\'analyse')),
                ('analyse_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analyses_sg_redigees', to=settings.AUTH_USER_MODEL, verbose_name='Analysé par')),
                ('courrier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_analyse_sg', to='courrier.courrier', verbose_name='Courrier')),
            ],
            options={
                'verbose_name': 'Fiche d\'analyse (SG)',
                'verbose_name_plural': 'Fiches d\'analyse (SG)',
            },
        ),
    ]
