# Generated by Django 4.2.30 on 2026-09-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0011_add_sg_and_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheanalysesg',
            name='direction_proposee',
            field=models.CharField(blank=True, choices=[('Cabinet du Ministre', 'Cabinet du Ministre'), ('Secrétariat Général', 'Secrétariat Général'), ('DAAF', 'DAAF'), ('DPDT', 'DPDT'), ('DPT', 'DPT'), ('DRICEHB', 'DRICEHB'), ('DLPL', 'DLPL'), ('DPAC', 'DPAC'), ('CNCIA', 'CNCIA'), ('DERPC', 'DERPC'), ('DPC', 'DPC'), ('CENALAC', 'CENALAC'), ('DRAC Grand-Lomé', 'DRAC Grand-Lomé'), ('DRAC Maritime', 'DRAC Maritime'), ('DRAC Plateaux', 'DRAC Plateaux'), ('DRAC Centrale', 'DRAC Centrale'), ('DRAC Kara', 'DRAC Kara'), ('DRAC Savanes', 'DRAC Savanes'), ('PRMP', 'PRMP'), ('CPMP', 'CPMP'), ('CCMP', 'CCMP'), ('Agent Comptable', 'Agent Comptable'), ('FPDT', 'FPDT'), ('FNPC', 'FNPC'), ('CNACET', 'CNACET'), ('IRES-RDEC', 'IRES-RDEC'), ('BUTODRA', 'BUTODRA'), ('CNPC', 'CNPC'), ('CRFTH', 'CRFTH'), ('CCT', 'CCT'), ('Autre', 'Autre (à préciser)')], max_length=150, null=True, verbose_name='Direction / Service proposé (Optionnel)'),
        ),
    ]
