# Generated by Django 6.0.1 on 2026-09-09 04:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0012_alter_ficheanalysesg_direction_proposee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire_role', models.CharField(blank=True, choices=[('SECRETARIAT_CENTRAL', 'Secrétariat Central'), ('SECRETAIRE_DC', 'Secrétaire du Directeur de Cabinet (DC)'), ('DC', 'Directeur de Cabinet (DC)'), ('SECRETAIRE_MINISTRE', 'Secrétaire Particulier du Ministre'), ('MINISTRE', 'Ministre'), ('SECRETAIRE_SG', 'Secrétaire du Secrétaire Général (SG)'), ('SG', 'Secrétaire Général (SG)'), ('DIRECTEUR', 'Directeur de Département'), ('AGENT', 'Agent')], max_length=50, null=True, verbose_name='Rôle ciblé')),
                ('service_concerne', models.CharField(blank=True, choices=[('Cabinet du Ministre', 'Cabinet du Ministre'), ('Secrétariat Général', 'Secrétariat Général'), ('DAAF', 'DAAF'), ('DPDT', 'DPDT'), ('DPT', 'DPT'), ('DRICEHB', 'DRICEHB'), ('DLPL', 'DLPL'), ('DPAC', 'DPAC'), ('CNCIA', 'CNCIA'), ('DERPC', 'DERPC'), ('DPC', 'DPC'), ('CENALAC', 'CENALAC'), ('DRAC Grand-Lomé', 'DRAC Grand-Lomé'), ('DRAC Maritime', 'DRAC Maritime'), ('DRAC Plateaux', 'DRAC Plateaux'), ('DRAC Centrale', 'DRAC Centrale'), ('DRAC Kara', 'DRAC Kara'), ('DRAC Savanes', 'DRAC Savanes'), ('PRMP', 'PRMP'), ('CPMP', 'CPMP'), ('CCMP', 'CCMP'), ('Agent Comptable', 'Agent Comptable'), ('FPDT', 'FPDT'), ('FNPC', 'FNPC'), ('CNACET', 'CNACET'), ('IRES-RDEC', 'IRES-RDEC'), ('BUTODRA', 'BUTODRA'), ('CNPC', 'CNPC'), ('CRFTH', 'CRFTH'), ('CCT', 'CCT'), ('Autre', 'Autre (à préciser)')], max_length=150, null=True, verbose_name='Direction / Service concerné')),
                ('etape', models.CharField(choices=[('ARRIVE', 'Enregistrement / Secrétariat'), ('REJET', 'Rejeté pour correction'), ('ANALYSE_DC', 'Analyse par le Directeur de Cabinet (DC)'), ('ANALYSE_SG', 'Analyse par le Secrétaire Général (SG)'), ('TRANSMISSION_MINISTRE', 'Transmission au Ministre'), ('DECISION', 'Décision du Ministre'), ('AFFECTATION', 'Affectation aux services'), ('TRAITEMENT_SERVICE', 'Traitement par le service / agent')], default='ARRIVE', max_length=50, verbose_name='Étape administrative')),
                ('date_debut_etape', models.DateTimeField(verbose_name="Date d'entrée à cette étape (réception / transmission)")),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de génération de l'alerte")),
                ('est_resolue', models.BooleanField(default=False, verbose_name='Alerte résolue')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='courrier.courrier', verbose_name='Courrier concerné')),
                ('destinataire_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances_recues', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ciblé')),
            ],
            options={
                'verbose_name': 'Alerte / Relance',
                'verbose_name_plural': 'Alertes et Relances',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['est_resolue', 'destinataire_role'], name='courrier_re_est_res_c51718_idx'), models.Index(fields=['est_resolue', 'destinataire_user'], name='courrier_re_est_res_22cd97_idx'), models.Index(fields=['courrier', 'est_resolue'], name='courrier_re_courrie_aab4ad_idx')],
            },
        ),
    ]
