# Generated by Django 6.0.1 on 2026-09-09 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0013_relance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationDelai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delai_jours', models.PositiveIntegerField(default=3, help_text="Nombre de jours sans traitement avant déclenchement d'une alerte et relance automatique.", verbose_name='Délai limite de traitement (en jours)')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dernière modification par')),
            ],
            options={
                'verbose_name': 'Configuration du délai de traitement',
                'verbose_name_plural': 'Configuration du délai de traitement',
            },
        ),
    ]
