# Generated by Django 5.2.17 on 2026-09-12 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0018_circuit_sg_dc'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='ancien_statut',
            field=models.CharField(blank=True, choices=[('ARRIVE', 'Enregistré (Secrétariat Central)'), ('REJETE_SECRETAIRE', 'Rejeté par Secrétariat pour correction'), ('TRANSMIS_SG', 'Transmis au SG'), ('EN_COURS_SG', "En cours d'analyse (SG)"), ('TRANSMIS_DC', 'Transmis au Secrétaire du DC'), ('EN_COURS_DC', "En cours d'analyse (DC)"), ('ANALYSE_VALIDE', 'Analyse validée (DC/SG)'), ('TRANSMIS_MINISTRE', 'Transmis au Ministre'), ('DECIDE', "Décidé (En attente d'affectation)"), ('AFFECTE', 'Affecté aux services'), ('TERMINE', 'Traité')], max_length=50, null=True, verbose_name='Ancien statut'),
        ),
        migrations.AddField(
            model_name='historique',
            name='direction',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Direction concernée'),
        ),
        migrations.AddField(
            model_name='historique',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_associes', to='courrier.document', verbose_name='Document associé'),
        ),
        migrations.AddField(
            model_name='historique',
            name='nouveau_statut',
            field=models.CharField(blank=True, choices=[('ARRIVE', 'Enregistré (Secrétariat Central)'), ('REJETE_SECRETAIRE', 'Rejeté par Secrétariat pour correction'), ('TRANSMIS_SG', 'Transmis au SG'), ('EN_COURS_SG', "En cours d'analyse (SG)"), ('TRANSMIS_DC', 'Transmis au Secrétaire du DC'), ('EN_COURS_DC', "En cours d'analyse (DC)"), ('ANALYSE_VALIDE', 'Analyse validée (DC/SG)'), ('TRANSMIS_MINISTRE', 'Transmis au Ministre'), ('DECIDE', "Décidé (En attente d'affectation)"), ('AFFECTE', 'Affecté aux services'), ('TERMINE', 'Traité')], max_length=50, null=True, verbose_name='Nouveau statut'),
        ),
        migrations.AddField(
            model_name='historique',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation éventuelle'),
        ),
        migrations.AddField(
            model_name='historique',
            name='role',
            field=models.CharField(blank=True, choices=[('SECRETARIAT_CENTRAL', 'Secrétariat Central'), ('SECRETAIRE_DC', 'Secrétaire du Directeur de Cabinet (DC)'), ('DC', 'Directeur de Cabinet (DC)'), ('SECRETAIRE_MINISTRE', 'Secrétaire Particulier du Ministre'), ('MINISTRE', 'Ministre'), ('SECRETAIRE_SG', 'Secrétaire du Secrétaire Général (SG)'), ('SG', 'Secrétaire Général (SG)'), ('DIRECTEUR', 'Directeur de Département'), ('AGENT', 'Agent')], max_length=50, null=True, verbose_name="Rôle de l'utilisateur"),
        ),
    ]
