# Generated by Django 5.2.17 on 2026-09-12 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0019_historique_ancien_statut_historique_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='reponse_requise',
            field=models.BooleanField(default=True, verbose_name='Une réponse écrite est requise pour ce courrier'),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='statut',
            field=models.CharField(choices=[('ARRIVE', 'Enregistré (Secrétariat Central)'), ('REJETE_SECRETAIRE', 'Rejeté par Secrétariat pour correction'), ('TRANSMIS_SG', 'Transmis au SG'), ('EN_COURS_SG', "En cours d'analyse (SG)"), ('TRANSMIS_DC', 'Transmis au Secrétaire du DC'), ('EN_COURS_DC', "En cours d'analyse (DC)"), ('ANALYSE_VALIDE', 'Analyse validée (DC/SG)'), ('TRANSMIS_MINISTRE', 'Transmis au Ministre'), ('DECIDE', "Décidé (En attente d'affectation)"), ('AFFECTE', 'Affecté aux services'), ('SOUMIS_DIRECTEUR', 'Soumis au Directeur pour validation'), ('CORRECTION_DEMANDEE', 'Correction demandée'), ('VALIDE_DIRECTEUR', 'Validé par le Directeur'), ('TERMINE', 'Traité')], default='ARRIVE', max_length=50, verbose_name='Statut du traitement'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='ancien_statut',
            field=models.CharField(blank=True, choices=[('ARRIVE', 'Enregistré (Secrétariat Central)'), ('REJETE_SECRETAIRE', 'Rejeté par Secrétariat pour correction'), ('TRANSMIS_SG', 'Transmis au SG'), ('EN_COURS_SG', "En cours d'analyse (SG)"), ('TRANSMIS_DC', 'Transmis au Secrétaire du DC'), ('EN_COURS_DC', "En cours d'analyse (DC)"), ('ANALYSE_VALIDE', 'Analyse validée (DC/SG)'), ('TRANSMIS_MINISTRE', 'Transmis au Ministre'), ('DECIDE', "Décidé (En attente d'affectation)"), ('AFFECTE', 'Affecté aux services'), ('SOUMIS_DIRECTEUR', 'Soumis au Directeur pour validation'), ('CORRECTION_DEMANDEE', 'Correction demandée'), ('VALIDE_DIRECTEUR', 'Validé par le Directeur'), ('TERMINE', 'Traité')], max_length=50, null=True, verbose_name='Ancien statut'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='nouveau_statut',
            field=models.CharField(blank=True, choices=[('ARRIVE', 'Enregistré (Secrétariat Central)'), ('REJETE_SECRETAIRE', 'Rejeté par Secrétariat pour correction'), ('TRANSMIS_SG', 'Transmis au SG'), ('EN_COURS_SG', "En cours d'analyse (SG)"), ('TRANSMIS_DC', 'Transmis au Secrétaire du DC'), ('EN_COURS_DC', "En cours d'analyse (DC)"), ('ANALYSE_VALIDE', 'Analyse validée (DC/SG)'), ('TRANSMIS_MINISTRE', 'Transmis au Ministre'), ('DECIDE', "Décidé (En attente d'affectation)"), ('AFFECTE', 'Affecté aux services'), ('SOUMIS_DIRECTEUR', 'Soumis au Directeur pour validation'), ('CORRECTION_DEMANDEE', 'Correction demandée'), ('VALIDE_DIRECTEUR', 'Validé par le Directeur'), ('TERMINE', 'Traité')], max_length=50, null=True, verbose_name='Nouveau statut'),
        ),
        migrations.CreateModel(
            name='ReponseCourrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_preparation', models.DateTimeField(auto_now_add=True, verbose_name='Date de préparation')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version de la réponse')),
                ('statut_traitement', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE_DIRECTEUR', 'Envoyée au Directeur'), ('CORRECTION', 'Retour pour correction'), ('VALIDE', 'Validée')], default='BROUILLON', max_length=40, verbose_name='Statut de la réponse')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation de correction')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reponses_courrier_redigees', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la réponse')),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_courrier', to='courrier.courrier', verbose_name='Courrier concerné')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses_associees', to='courrier.document', verbose_name='Document de réponse')),
            ],
            options={
                'verbose_name': 'Réponse du courrier',
                'verbose_name_plural': 'Réponses du courrier',
                'ordering': ['-version', '-date_preparation'],
            },
        ),
    ]
