# Generated by Django 5.2.17 on 2026-09-12 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0020_courrier_reponse_requise_alter_courrier_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='document_signe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_signees', to='courrier.document', verbose_name='Document signé par le Ministre'),
        ),
    ]
