# Generated by Django 5.2.17 on 2026-09-12 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0021_decision_document_signe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='statut',
            field=models.CharField(choices=[('ARRIVE', 'Enregistré (Secrétariat Central)'), ('REJETE_SECRETAIRE', 'Rejeté par Secrétariat pour correction'), ('TRANSMIS_SG', 'Transmis au SG'), ('EN_COURS_SG', "En cours d'analyse (SG)"), ('TRANSMIS_DC', 'Transmis au Secrétaire du DC'), ('EN_COURS_DC', "En cours d'analyse (DC)"), ('ANALYSE_VALIDE', 'Analyse validée (DC/SG)'), ('TRANSMIS_MINISTRE', 'Transmis au Ministre'), ('DECIDE', "Décidé (En attente d'affectation)"), ('SIGNE_PAR_MINISTRE', 'Signé par le Ministre'), ('COURRIER_SORTANT', 'Courrier sortant enregistré'), ('AFFECTE', 'Affecté aux services'), ('SOUMIS_DIRECTEUR', 'Soumis au Directeur pour validation'), ('CORRECTION_DEMANDEE', 'Correction demandée'), ('VALIDE_DIRECTEUR', 'Validé par le Directeur'), ('TERMINE', 'Traité')], default='ARRIVE', max_length=50, verbose_name='Statut du traitement'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='ancien_statut',
            field=models.CharField(blank=True, choices=[('ARRIVE', 'Enregistré (Secrétariat Central)'), ('REJETE_SECRETAIRE', 'Rejeté par Secrétariat pour correction'), ('TRANSMIS_SG', 'Transmis au SG'), ('EN_COURS_SG', "En cours d'analyse (SG)"), ('TRANSMIS_DC', 'Transmis au Secrétaire du DC'), ('EN_COURS_DC', "En cours d'analyse (DC)"), ('ANALYSE_VALIDE', 'Analyse validée (DC/SG)'), ('TRANSMIS_MINISTRE', 'Transmis au Ministre'), ('DECIDE', "Décidé (En attente d'affectation)"), ('SIGNE_PAR_MINISTRE', 'Signé par le Ministre'), ('COURRIER_SORTANT', 'Courrier sortant enregistré'), ('AFFECTE', 'Affecté aux services'), ('SOUMIS_DIRECTEUR', 'Soumis au Directeur pour validation'), ('CORRECTION_DEMANDEE', 'Correction demandée'), ('VALIDE_DIRECTEUR', 'Validé par le Directeur'), ('TERMINE', 'Traité')], max_length=50, null=True, verbose_name='Ancien statut'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='nouveau_statut',
            field=models.CharField(blank=True, choices=[('ARRIVE', 'Enregistré (Secrétariat Central)'), ('REJETE_SECRETAIRE', 'Rejeté par Secrétariat pour correction'), ('TRANSMIS_SG', 'Transmis au SG'), ('EN_COURS_SG', "En cours d'analyse (SG)"), ('TRANSMIS_DC', 'Transmis au Secrétaire du DC'), ('EN_COURS_DC', "En cours d'analyse (DC)"), ('ANALYSE_VALIDE', 'Analyse validée (DC/SG)'), ('TRANSMIS_MINISTRE', 'Transmis au Ministre'), ('DECIDE', "Décidé (En attente d'affectation)"), ('SIGNE_PAR_MINISTRE', 'Signé par le Ministre'), ('COURRIER_SORTANT', 'Courrier sortant enregistré'), ('AFFECTE', 'Affecté aux services'), ('SOUMIS_DIRECTEUR', 'Soumis au Directeur pour validation'), ('CORRECTION_DEMANDEE', 'Correction demandée'), ('VALIDE_DIRECTEUR', 'Validé par le Directeur'), ('TERMINE', 'Traité')], max_length=50, null=True, verbose_name='Nouveau statut'),
        ),
        migrations.CreateModel(
            name='CourrierSortant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.CharField(max_length=255)),
                ('objet', models.CharField(blank=True, max_length=255)),
                ('reference_sortie', models.CharField(blank=True, max_length=100, unique=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True)),
                ('courrier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courrier_sortant', to='courrier.courrier')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_sortants', to='courrier.document')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courriers_sortants_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
