# Generated by Django 5.2.17 on 2026-09-12 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0022_alter_courrier_statut_alter_historique_ancien_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courriersortant',
            name='date_expedition',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'expédition"),
        ),
    ]
