# Generated by Django 5.2.17 on 2026-09-12 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0023_courriersortant_date_expedition'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionFinale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions_finales', models.TextField(blank=True)),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('courrier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_finale', to='courrier.courrier')),
                ('document_signe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions_finales_signees', to='courrier.document')),
                ('signe_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions_finales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Décision finale après traitement',
                'verbose_name_plural': 'Décisions finales après traitement',
            },
        ),
    ]
