# Generated by Django 5.2.17 on 2026-09-12 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0024_decisionfinale'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheanalyse',
            name='analyse_sg_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses_sg_sur_fiches', to=settings.AUTH_USER_MODEL, verbose_name='Analysé par le SG'),
        ),
        migrations.AddField(
            model_name='ficheanalyse',
            name='date_analyse_sg',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheanalyse',
            name='date_validation_sg',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheanalyse',
            name='observations_sg',
            field=models.TextField(blank=True, verbose_name='Observations du SG'),
        ),
        migrations.AddField(
            model_name='ficheanalyse',
            name='propositions_sg',
            field=models.TextField(blank=True, verbose_name='Propositions du SG'),
        ),
        migrations.AddField(
            model_name='ficheanalyse',
            name='valide_sg',
            field=models.BooleanField(default=False, verbose_name='Analyse SG validée'),
        ),
    ]
