# Generated by Django 6.1 on 2026-09-14 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0026_backfill_ficheanalyse_sg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courriersortant',
            name='date_expedition',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name="Date d'expédition"),
        ),
    ]
