# Generated by Django 6.1 on 2026-09-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0027_alter_courriersortant_date_expedition'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteurCourrierSortant',
            fields=[
                ('annee', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dernier_numero', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
